# Generated by Django 5.2.5 on 2025-09-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='original_url',
        ),
        migrations.AddField(
            model_name='video',
            name='embed_url',
            field=models.URLField(blank=True, verbose_name='Embed-ссылка'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
