# Generated by Django 5.2.5 on 2025-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_phone_number_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='education',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='vk_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на VK'),
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
